### ISSUE TITLE
Reading from stdin at the start of the program

### ISSUE THREAD

**Issue by marlun** [mafintosh/diffy#4]
How would I use this but at the same time accept data being passed to this program on stdin?

    ls -l | <program>

If I try

    process.stdin.pipe(concat(list))

I get the following messge
```     
process.stdin.setRawMode(true)
              ^
TypeError: process.stdin.setRawMode is not a function
    at neatInput (<rest of path>/node_modules/neat-input/index.js:25:17)
```

**Comment by mafintosh** [comment]
Fixed in latest neat-input. If you reinstall it should work as expected. If not post the program and I'll try helping :)

**Comment by marlun** [comment]
It seem to have helped with the error but I'm still a little lost. Hopefully it's an obvious error on my part:

```javascript
var concat = require('concat-stream')
var diffy = require('diffy')({ fullscreen: true })
var fs = require('fs')
var input = require('diffy/input')()
var Menu = require('menu-string')

var menu

process.stdin.pipe(concat(list))

input.on('keypress', function (ch, key) {
  if (ch === 'q') process.exit()
})

function list (data) {
  var items = data.toString()
    .split('\n')
    .filter(s => s)
    .map(str => ({ text: str }))
  menu = new Menu({
    items: items
  })
  diffy.render(function () {
    return menu.toString()
  })
  menu.on('update', function () {
    diffy.render()
  })
  diffy.render()
}
```

**Comment by mafintosh** [comment]
Can you show what input you are piping to it? Prob my fault

**Comment by marlun** [comment]
I just do `ls -l | node index.js`, do you want the specific input?

**Comment by mafintosh** [comment]
where is q coming from in the above example then?

**Comment by marlun** [comment]
Keyboard? :) I want to be able to do like `ls -l | node index.js` and then (yet to be implemented) j/k to choose a line and hit ENTER to get it to output that line. The 'q' is only there to make it easy for me to exit by hitting 'q'.

**Comment by mafintosh** [comment]
When doing `ls -l | node index.js` stdin of your application is taken over by `ls -l`. You cannot do both unfortunately :) Another way would be to have `index.js` spawn `ls -l` instead, and have stdin be interactive

**Comment by marlun** [comment]
I was inspired by https://github.com/junegunn/fzf where I can do `ls -l | fzf` and then filter by writing a string and hit enter.

**Comment by mafintosh** [comment]
Oh interesting. Maybe there is a way to do it then! Let me take a look tmw

**Comment by marlun** [comment]
This might not be a very good solution but what about splitting the program into two parts, one that reads from stdin, saves it to a temporary file and runs a second program in a new process. The new program is given the path to the temporary file which it reads from and shows it in a menu-string. The second program should be able to be interactive :)

I made a first try but this is not working:
### index.js
```javascript
var concat = require('concat-stream')
var exec = require('child_process').exec
var fs = require('fs')
var tmp = require('tmp')

process.stdin.pipe(concat(saveFile))

function saveFile (data) {
  tmp.file(function (err, path, fd, cleanup) {
    if (err) throw err
    fs.writeFile(path, data, function (err) {
      if (err) throw err
      exec('node menu.js ' + path, function (err, stdout, stderr) {
        if (err) throw err
        console.log(stdout)
        cleanup()
      })
    })
  })
}
```
### menu.js
```javascript
var diffy = require('diffy')({ fullscreen: true })
var fs = require('fs')
var input = require('diffy/input')()
var Menu = require('menu-string')

var menu;

input.on('enter', function () {
  var item = menu.selected
  console.log(item)
})

load(process.argv[2], function (lines) {
  menu = new Menu({
    items: lines
  })
  diffy.render(function () {
    return menu.toString()
  })
  menu.on('update', function () {
    diffy.render()
  })
  diffy.render()
})

function load (path, cb) {
  fs.readFile(path, 'utf8', function (err, data) {
    if (err) throw err
    cb(data.split('\n'))
  })
}
```

**Comment by marlun** [comment]
Did you look into this further?
